#################### default parameters ################################
# favicon
favicon = "images/favicon.png"

# logo
logo = "images/logo.png"

# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "148px"

# if logo_webp set false, will not generate WEBP version of logo | default is true
logo_webp = true

# logo text will only show when logo is missing.
logo_text = "BRB Robotics"

# purgeCSS
purge_css = true

# search
search = true

# Main Sections
mainSections = ["blog"]

# image gallery shortcode
image_gallery = false

# contact form action
contact_form_action = "#" # contact form works with [https://airform.io/] or [https://formspree.io]

# google tag manager, see https://developers.google.com/tag-manager/
google_tag_manager = "" # example: G-XXXXXXXXXX
google_adsense = ""     # example: ca-pub-xxxxxxxxxxxxxxxx

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"
custom_script = ""

# copyright
theme_copyright = false

# Preloader
[preloader]
enable = false
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = false
label = "sign up"
link = "#"

# contact info
[contact_info]
address = "2171 Ivy Road, Suite 5, Charlottesville, VA 22903"
mobile = "+(434) 688-6119"
email = "ftc.26502.brb.robotics@gmail.com"

# google_map
[google_map]
enable = false
embed_url = ""

# Subscription
[subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# Crisp Chat
[crisp_chat]
enable = false
crisp_website_id = "9aa449e1-9999-422a-938f-8567982eec6d" # replace this code with yours
# Check this video tutorial to get your crisp website ID - https://www.youtube.com/watch?v=nW5UX6iVdFc

# seo meta data for OpenGraph / Twitter Card
[metadata]
keywords = ["FTC", "FIRST", "BRB Robotics", "Robotics", "STEM", "Education"]
description = "FTC Team 26502 is dedicated to building robots and inspiring the next generation of STEM innovators."
author = "BRB Robotics"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own

# matomo tracking: see https://matomo.org/
[matomo]
enable = false
url = ""       # your matomo url
id = ""        # your matomo id

# baidu analytics: see https://tongji.baidu.com/
[baidu]
enable = false
analytics_id = "" # Your ID

# plausible analytics: see https://plausible.io/
[plausible]
enable = false
domain = ""    # yourdomain.com

# counter analytics: see https://counter.dev/setup.html
[counter]
enable = false
username = ""  # your username

# site verifications
[site_verification]
google = ""   # Your verification code
bing = ""     # Your verification code
baidu = ""    # Your verification code
facebook = "" # Your verification code
mastodon = "" # Your verification code

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

############################# social site ########################
[[social]]
title = "facebook"
icon = "fab fa-facebook" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.facebook.com/brbrobotics"

[[social]]
title = "instagram"
icon = "fab  fa-instagram" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.instagram.com/ftcteam26502brbrobotics/"

[[social]]
title = "github"
icon = "fab  fa-github" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://github.com/FTC-Team-26502"

[[social]]
title = "youtube"
icon = "fab  fa-youtube" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.youtube.com/@FTCBRB-Robotics26502"

############################# Colors ##############################


# DON'T REMOVE THIS FILE.
# This file is for render site varibles and plugins
#
# The actual configuration files are stored in the `config/_default/` folder.

######################### site variables ##############################
# site variables
[variables]
black = "#000000"
white = "#ffffff"
gray = "#f8f9fa"
bg_secondary = "#b7ffb0"
bg_gradient_primary = "linear-gradient(80deg, #159957 0%, #b7ffb0 100%)"
bg_gradient_secondary = "linear-gradient(80deg, #ff9ad4 0%, #fce7ff 100%)"
color_primary = "#b7ffb0"
color_secondary = "#159957"
text_dark = "#159957"
text_light = "#fd00d3"
text_color = "#000000"
border_color = "#159957"
border_light = "#ffdcfa"

dark_pink = "#fd00d3"
light_pink = "#ffdcfa"
dark_green = "#159957"
light_green = "#b7ffb0"

# color_primary = "#007ac7"
# color_secondary = "#00e0d8"
# bg_secondary = "#15192b"
# text_dark = "#242f3e"
# text_color = "#8b8e93"
# text_light = "#d4dae3"
text_color_light = "#959595"
# border_color = "#dee2e6"
# border_light = "#2d3041"
# bg_gradient_primary = "linear-gradient(134deg, #00a4db 0%, #00269e 100%)"
# bg_gradient_secondary = "linear-gradient( 80deg, rgb(0,48,204) 0%, rgb(0,164,219) 100%)"
btn_gradient_primary = "linear-gradient(45deg, rgb(0, 168, 244) 0%, rgb(2, 209, 161) 100%)" 

# font variables
# base font size for full website, 
font_size = "16px" # default is 16px

# Font Scale Sizes
# "minorSecond": 1.067,
# "majorSecond": 1.125,
# "minorThird": 1.2,
# "majorThird": 1.25,
# "perfectFourth": 1.333,
# "augmentedFourth": 1.414,
# "perfectFifth": 1.5,
# "goldenRatio": 1.618
font_scale = "1.205" # default is "majorThird": 1.25

# Give your font name from google font. add font weight using ":wght@" and separate by ";"
# example: "Work Sans:wght@400;500;600"
font_primary = "Poppins:wght@300;400;500;600;700"
font_primary_type = "sans-serif" # [serif/sans-serif]
font_secondary = "Open Sans:wght@300;400;600;700;800"
font_secondary_type = "sans-serif" # [serif/sans-serif]
font_icon = "Font Awesome 6 Free"


############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]] 
link = "plugins/aos/aos.css"
[[params.plugins.css]] 
link = "plugins/swiper/swiper.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/solid.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/icons.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/brands.css"
[[params.plugins.css]]
link = "assets/css/custom.css" 

# JS Plugins
[[params.plugins.js]]
link = "plugins/cookie.js"
[[params.plugins.js]]
link = "plugins/aos/aos.js"
[[params.plugins.js]]
link = "plugins/swiper/swiper.min.js"
[[params.plugins.js]]
link = "plugins/webfont/webfont-loader-2.js"

